-- INNER JOIN | CONSULTA LOS CLIENTES Y SU VENDEDOR
SELECT
	C.NOMBRE AS CLIENTE,
    C.BARRIO,
    V.NOMBRE AS VENDEDOR
FROM
	tabla_de_clientes AS C
    INNER JOIN
    tabla_de_vendedores AS V
    ON C.BARRIO = V.BARRIO;
    
-- LEFT JOIN | CONSULTA LOS CLIENTES QUE NO TIENEN VENDEDOR
SELECT
	C.NOMBRE AS CLIENTE,
    C.BARRIO,
    V.NOMBRE AS VENDEDOR
FROM
	tabla_de_clientes AS C
    LEFT JOIN
    tabla_de_vendedores AS V
    ON C.BARRIO = V.BARRIO;
    
-- RIGHT JOIN | CONSULTA LOS VENDEDORES QUE ESTAN DE VACACIONES
SELECT
	C.NOMBRE AS CLIENTE,
    C.BARRIO,
    V.NOMBRE AS VENDEDOR,
    V.VACACIONES
FROM
	tabla_de_clientes AS C
    RIGHT JOIN
    tabla_de_vendedores AS V
    ON C.BARRIO = V.BARRIO;
    
-- CROSS JOIN
SELECT
	C.NOMBRE AS CLIENTE,
    C.BARRIO,
    V.NOMBRE AS VENDEDOR
FROM
	tabla_de_clientes AS C,
    tabla_de_vendedores AS V
WHERE C.BARRIO = V.BARRIO;

