SELECT
	COUNT(*)
FROM
	tabla_de_clientes;
    
-- INNER JOIN    
SELECT DISTINCT
	C.DNI,
    C.NOMBRE,
    F.DNI AS FACTURA_DNI
FROM
	TABLA_DE_CLIENTES AS C
    INNER JOIN
    FACTURAS F
	ON C.DNI = F.DNI; 
    
-- LEFT JOIN | CONSULTA LOS CLIENTES QUE AUN NO HAN REALIZADO COMPRAS
SELECT DISTINCT
	C.DNI,
    C.NOMBRE,
    F.DNI AS FACTURA_DNI
FROM
	TABLA_DE_CLIENTES AS C
    LEFT JOIN
    FACTURAS F
	ON C.DNI = F.DNI
WHERE
	F.DNI IS NULL;
    
-- LEFT JOIN | CONSULTA LAS FACTURAS QUE NO CORRESPONDE A NINGUN CLIENTE
SELECT DISTINCT
	C.DNI AS CLIENTE_DNI,
    C.NOMBRE,
    F.DNI
FROM
	TABLA_DE_CLIENTES AS C
    RIGHT JOIN
    FACTURAS F
	ON F.DNI = C.DNI
WHERE
	C.DNI IS NULL;