-- ADDDATE, AÑADE UN INTERVALO A UNA FECHA
SELECT 
	ADDDATE(
		CURRENT_DATE(),
        INTERVAL 1 DAY
    );
    
-- CURRENTDATE, OBTIENE LA FECHA ACTUAL DEL SERVIDOR
SELECT 
	CURRENT_DATE();

-- CURRENTTIMESTAMP, OBTIENE DIA Y HORA EXACTOS DEL SERVIDOR
SELECT 
	CURRENT_TIMESTAMP();

-- DATE, IMPRIME UNA FECHA QUE SE PASA EN FORMARO YYYY-MM-DD
SELECT
	DATE('2024-01-01');

-- DATEDIFF, DEVUELVE LA DIFERENCIA ENTRE FECHAS
SELECT 
	DATEDIFF('2024-01-01','2017-01-01')/365;
    
-- DAY, DEVUELVE EL DIA DEL MES DE UNA FECHA
SELECT 
	DAY(
		CURRENT_DATE()
	);
    
-- DAYNAME, DEVUELVE EL NOMBRE DEL DIA DE LA SEMANA
SELECT
	DAYNAME(
		CURRENT_DATE()
	);

-- LOCALTIMESTAMP, DEVUELVE LA HORA LOCAL
SELECT 
	LOCALTIMESTAMP();
    
-- YEAR, DEUVELVE UN AÑO
SELECT
	YEAR(
		CURRENT_DATE()
    );
    
-- MONTHNAME, DEVUELVE EL NOMBRE DEL MES
SELECT
	MONTHNAME(
		CURRENT_DATE()
    );

-- DATESUB, PERMITE RESTAS INTERVALOS DE TIEMPO
SELECT 
	DATE_SUB(
		CURRENT_DATE,
        INTERVAL 1 DAY
    );
	
