-- INFORME DE VENTAS POR SABOR EN EL AÑO 2016
-- CANTIDAD DE LITROS
-- PARTICIPACION DE MAYOR A MENOS
USE JUGOS_VENTAS;

-- CANTIDAD VENDIDA POR SABOR
SELECT
	P.SABOR,
    SUM(I.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS AÑO
FROM
	TABLA_DE_PRODUCTOS P
    INNER JOIN
    ITEMS_FACTURAS I
    ON
    P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
    INNER JOIN
    FACTURAS F
    ON
    F.NUMERO = I.NUMERO
WHERE
	YEAR(F.FECHA_VENTA) = 2016
GROUP BY
	P.SABOR,
    YEAR(F.FECHA_VENTA)
ORDER BY SUM(I.CANTIDAD) DESC;

-- CANTIDAD TOTAL POR AÑO
SELECT
    SUM(I.CANTIDAD) AS CANTIDAD_TOTAL,
    YEAR(F.FECHA_VENTA) AS AÑO
FROM
	TABLA_DE_PRODUCTOS P
    INNER JOIN
    ITEMS_FACTURAS I
    ON
    P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
    INNER JOIN
    FACTURAS F
    ON
    F.NUMERO = I.NUMERO
WHERE
	YEAR(F.FECHA_VENTA) = 2016
GROUP BY
    YEAR(F.FECHA_VENTA);
    
-- INFORME FINAL CON PORCENTAJE DE GANANCIAS
SELECT 
	VENTAS_SABOR.SABOR,
    VENTAS_SABOR.AÑO,
    VENTAS_SABOR.CANTIDAD_TOTAL,
    ROUND((VENTAS_SABOR.CANTIDAD_TOTAL / VENTA_TOTAL.CANTIDAD_TOTAL) * 100,2) AS PORCENTAJE_DE_GANACIAS
FROM
	(
		SELECT
			P.SABOR,
			SUM(I.CANTIDAD) AS CANTIDAD_TOTAL,
			YEAR(F.FECHA_VENTA) AS AÑO
		FROM
			TABLA_DE_PRODUCTOS P
			INNER JOIN
			ITEMS_FACTURAS I
			ON
			P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
			INNER JOIN
			FACTURAS F
			ON
			F.NUMERO = I.NUMERO
		WHERE
			YEAR(F.FECHA_VENTA) = 2016
		GROUP BY
			P.SABOR,
			YEAR(F.FECHA_VENTA)
		ORDER BY SUM(I.CANTIDAD) DESC
    ) AS VENTAS_SABOR
INNER JOIN
	(
		-- CANTIDAD TOTAL POR AÑO
		SELECT
			SUM(I.CANTIDAD) AS CANTIDAD_TOTAL,
			YEAR(F.FECHA_VENTA) AS AÑO
		FROM
			TABLA_DE_PRODUCTOS P
			INNER JOIN
			ITEMS_FACTURAS I
			ON
			P.CODIGO_DEL_PRODUCTO = I.CODIGO_DEL_PRODUCTO
			INNER JOIN
			FACTURAS F
			ON
			F.NUMERO = I.NUMERO
		WHERE
			YEAR(F.FECHA_VENTA) = 2016
		GROUP BY
			YEAR(F.FECHA_VENTA)
    ) AS VENTA_TOTAL
ON VENTA_TOTAL.AÑO = VENTAS_SABOR.AÑO
ORDER BY
	VENTAS_SABOR.CANTIDAD_TOTAL DESC;