-- INFORME DE CLIENTES QUE HAN REALIZADO COMPRAS VALIDAS E INVALIDAS CADA MES
-- COMPRA VALIDA -> EL CLIENTE ADQUIERE EL VOLUMEN DE JUGO PERMITIDO ASIGNADO
-- COMPRA INVALIDA -> EL CLIENTE EXCEDE EL VOLUMEN DE JUGO PERMITIDO  ASIGNADO
    
SELECT
	F.DNI,
    I.CANTIDAD,
    DATE_FORMAT(F.FECHA_VENTA,"%m - %Y") AS FECHA
FROM
	FACTURAS F
    INNER JOIN
    ITEMS_FACTURAS I
    ON I.NUMERO = F.NUMERO;
    
-- CANTIDAD DE VENTAS AL MES POR CLIENTE
SELECT
	F.DNI,
    SUM(I.CANTIDAD) TOTAL,
    DATE_FORMAT(F.FECHA_VENTA,"%m - %Y") AS FECHA
FROM
	FACTURAS F
    INNER JOIN
    ITEMS_FACTURAS I
    ON I.NUMERO = F.NUMERO
GROUP BY
	F.DNI,
	I.CANTIDAD,
	F.FECHA_VENTA;
    
-- LIMITE DE VENTAS POR CLIENTE EN DECILITROS
SELECT 
	DNI,
    NOMBRE,
    VOLUMEN_DE_COMPRA
FROM
	tabla_de_clientes AS C;
    
-- UNION
SELECT
    C.NOMBRE,
    C.VOLUMEN_DE_COMPRA / 10 AS CANTIDAD_MAXIMA,
	F.DNI,
    SUM(I.CANTIDAD) AS CANTIDAD_VENDIDA,
    DATE_FORMAT(F.FECHA_VENTA,"%m - %Y") AS "FECHA DE COMPRA"
FROM
	FACTURAS F
INNER JOIN
    ITEMS_FACTURAS I
    ON I.NUMERO = F.NUMERO
INNER JOIN
    TABLA_DE_CLIENTES C
    ON C.DNI = F.DNI
GROUP BY
	C.NOMBRE,
	F.DNI,
	 DATE_FORMAT(F.FECHA_VENTA,"%m - %Y");
     
-- FILTRANDO POR COMPRAS VALIDAS
SELECT 
	A.DNI,
    A.NOMBRE,
	CANTIDAD_VENDIDA - CANTIDAD_MAXIMA AS DIFERENCIA,
    A.FECHA_DE_COMPRA
FROM
	(
		SELECT
			C.NOMBRE,
			C.VOLUMEN_DE_COMPRA / 10 AS CANTIDAD_MAXIMA,
			F.DNI,
			SUM(I.CANTIDAD) AS CANTIDAD_VENDIDA,
			DATE_FORMAT(F.FECHA_VENTA,"%m - %Y") AS FECHA_DE_COMPRA
		FROM
			FACTURAS F
		INNER JOIN
			ITEMS_FACTURAS I
			ON I.NUMERO = F.NUMERO
		INNER JOIN
			TABLA_DE_CLIENTES C
			ON C.DNI = F.DNI
		GROUP BY
			C.NOMBRE,
			F.DNI,
			DATE_FORMAT(F.FECHA_VENTA,"%m - %Y")
    ) AS A;
    
-- CLASIFICANDO
SELECT 
	A.DNI,
    A.NOMBRE,
	CANTIDAD_VENDIDA - CANTIDAD_MAXIMA AS DIFERENCIA,
    A.FECHA_DE_COMPRA,
CASE    
	WHEN CANTIDAD_VENDIDA - CANTIDAD_MAXIMA < 0 
    THEN "VENTA VALIDA"
    ELSE "VENTA NO VALIDA"
END AS STATUS_VENTA
FROM
	(
		SELECT
			C.NOMBRE,
			C.VOLUMEN_DE_COMPRA / 10 AS CANTIDAD_MAXIMA,
			F.DNI,
			SUM(I.CANTIDAD) AS CANTIDAD_VENDIDA,
			DATE_FORMAT(F.FECHA_VENTA,"%m - %Y") AS FECHA_DE_COMPRA
		FROM
			FACTURAS F
		INNER JOIN
			ITEMS_FACTURAS I
			ON I.NUMERO = F.NUMERO
		INNER JOIN
			TABLA_DE_CLIENTES C
			ON C.DNI = F.DNI
		GROUP BY
			C.NOMBRE,
			F.DNI,
			DATE_FORMAT(F.FECHA_VENTA,"%m - %Y")
    ) AS A;

    
