USE jugos_ventas;

-- CONSULTA TODOS LOS REGISTROS QUE CONTENGAN UN CAMPO DE LA TABLA BARRIO
SELECT DISTINCT
	*
FROM
	TABLA_DE_CLIENTES
WHERE 
	BARRIO IN 
    (
		'condesa','del valle',
		'contadoro',
		'Oblatos'
    );
	
-- CONSULTA TODOS LOS REGISTROS QUE CONTENGAN UN CAMPO DE BARRIO
SELECT DISTINCT
	*
FROM
	TABLA_DE_CLIENTES
WHERE 
	BARRIO IN 
    (
		SELECT DISTINCT
			BARRIO
		FROM
			TABLA_DE_VENDEDORES
    );
    
-- CONSULTA EL PRECIO MAXIMO DE PRODUCTO POR ENVASE
SELECT 
	ENVASE,
    MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO
FROM
	TABLA_DE_PRODUCTOS
GROUP BY
	ENVASE;
    
-- CONSULTA EL PRECIO MAXIMO POR ENVASE Y QUE SEA MAYOR A 10    
SELECT
	X.ENVASE,
    X.PRECIO_MAXIMO
FROM 
	(
		SELECT 
			ENVASE,
			MAX(PRECIO_DE_LISTA) AS PRECIO_MAXIMO
		FROM
			TABLA_DE_PRODUCTOS
		GROUP BY
			ENVASE
	) X
WHERE
	X.PRECIO_MAXIMO >= 10;