-- CONSULTA LOS PRODUCTOS ORDENADOS POR SU PRECIO EN ORDEN ASCENDENTE
SELECT 
	* 
FROM 
	tabla_de_productos
ORDER BY
	precio_de_lista;
    
-- CONSULTA LOS PRODUCTOS ORDENADOS POR SU PRECIO EN ORDEN DESENDENTE
SELECT 
	* 
FROM 
	tabla_de_productos
ORDER BY
	precio_de_lista
DESC;

-- CONSULTA LOS PRODUCTOS ORDENADOS POR SU PRECIO EN ORDEN ASCENDENTE (A-Z)
SELECT 
	* 
FROM 
	tabla_de_productos
ORDER BY
	nombre_del_producto;
    
-- CONSULTA LOS PRODUCTOS ORDENADOS POR SU PRECIO EN ORDEN DESCENDENTE (Z-A)
SELECT 
	* 
FROM 
	tabla_de_productos
ORDER BY
	precio_de_lista DESC;
    
-- CONSULTA LOS PRODUCTOS ORDENADOS POR SU PRECIO EN ORDEN DESCENDENTE Y EL ENVASE EN ORDEN ASC
SELECT 
	* 
FROM 
	tabla_de_productos
ORDER BY
	envase ASC,
	precio_de_lista DESC;