-- USAR LA BASE MUNDO
USE WORLD;

-- SELECCIONA TODO DE LA TABLA CIUDAD 
SELECT * FROM CITY;

-- SELECCIONA TODO DE LA TABLA PAIS
SELECT * FROM COUNTRY;

-- SELECCIONA TODO DE LA TABLA LENGUAJE CIUDAD
SELECT * FROM COUNTRYLANGUAGE;

