-- CREAR DB JUGOS
CREATE DATABASE IF NOT EXISTS jugos;

-- USAR LA DB JUGOS
USE jugos;

-- CREAR ESQUEMA CON ESPACIOS EN BLANCO 
CREATE SCHEMA IF NOT EXISTS `EXAMPLE 3`;

-- ELIMINAR EL ESQUEMA EXAMPLE 3
DROP SCHEMA IF EXISTS `EXAMPLE 3`; 