-- BORRAR REGISTRO
DELETE FROM productos
WHERE producto = "773912";

-- CONSULTAR REGISTROS DE LA TABLA
SELECT * FROM PRODUCTOS;

-- DROP se utiliza para elementos de una DB
-- DELETE SE UTILIZA PARA REGISTROS