-- MUESTRA TODAS LAS VARIABLES QUE CONTENGAR dir AL FINAL DE SU NOMBRE
SHOW VARIABLES WHERE Variable_Name LIKE '%dir';

-- 'datadir' ALMACENA LA RUTA DONDE SE GUARDAN LAS DB
-- 'C:\ProgramData\MySQL\MySQL Server 8.0\Data\'

-- PARA CAMBIAR LA RUTA DONDE SE ALMACENAN LAS DB DEBE HACERCE DESDE EL ARCHIVO INI
-- SE RECOMIENDA UNICAMENTE COMENTAR LA RUTA ANTERIOR 

-- UNA VEZ REALIZADOS LOS CAMBIOS EN EL ARCHIVO INI, SE DEBE REINICIAR EL SERVICIO DE MYSQL