-- CREA UN USURIO NORMAL
CREATE USER 'user02'@'localhost' IDENTIFIED BY 'user02';

-- OTROGA PERMISOS
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE ON *.* TO 'user02'@'localhost';