-- CREA USUARIO 
CREATE USER 'user04'@'%' IDENTIFIED BY 'user04';

-- ASIGNA PRIVILEGIOS Y ACCESOS
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE ON empresa.* TO 'user04'@'%';

-- CREA USUARIO 
CREATE USER 'user05'@'%' IDENTIFIED BY 'user05';

-- ASIGNA PRIVILEGIOS Y ACCESOS
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE ON empresa.productos TO 'user05'@'%';