-- MUESTRA A LOS DIFERENTES USUARIOS Y SUS PRIVILEGIOS
SELECT * FROM mysql.user;

-- MUESTRA LOS PRIVILEGIOS DE UN USUARIO ESPECIFICO
SHOW GRANTS FOR 'user01'@'localhost';

-- QUITA LOS PRIVILEGIOS A UN USUARIO ESPECIFICO
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'user01'@'localhost';