-- TABLAS CREADAS EN DISCO
SHOW GLOBAL STATUS LIKE 'Created_tmp_disk_tables';

-- TABLAS CREADAS EN MEMORIA RAM
SHOW GLOBAL STATUS LIKE 'Created_tmp_tables';

-- MUESTRA EL TAMAÑO EN BITES DONDE SE ESCRIBEN LAS TABLAS
SHOW GLOBAL VARIABLES LIKE 'tmp_table_size';

-- CAMBIA EL VALOR DE LA VARIABLE tmp_table_size
SET GLOBAL tmp_table_size = 10485860;