CREATE TABLE `tb_producto2` (
  `CODIGO` varchar(10) NOT NULL,
  `DESCRIPCION` varchar(100) DEFAULT NULL,
  `SABOR` varchar(50) DEFAULT NULL,
  `TAMAÑO` varchar(50) DEFAULT NULL,
  `ENVASE` varchar(50) DEFAULT NULL,
  `PRECIO_LISTA` float DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
);


INSERT INTO TB_PRODUCTO2
		SELECT * FROM TB_PRODUCTO;
        
UPDATE tb_producto2
SET PRECIO_LISTA = PRECIO_LISTA * 1.15;

DELETE FROM TB_PRODUCTO2;

DROP TABLE TB_PRODUCTO2;