USE VENTAS_JUGOS;

-- TABLA DE VENTAS
CREATE TABLE IF NOT EXISTS
	TB_VENTAS
    (
		NUMERO VARCHAR(5) NOT NULL,
        FECHA DATE NOT NULL,
        DNI VARCHAR(11) NOT NULL,
        MATRICULA VARCHAR(5) NOT NULL,
        IMPUESTO FLOAT,
        
        PRIMARY KEY(NUMERO)
    );
    
-- AGREGAR CLAVES EXTERNAS
ALTER TABLE 
	TB_VENTAS ADD CONSTRAINT
		FK_CLIENTE FOREIGN KEY(DNI) REFERENCES TB_CLIENTE(DNI);

ALTER TABLE 
	TB_VENTAS ADD CONSTRAINT
		FK_VENDEDOR FOREIGN KEY(MATRICULA) REFERENCES TB_VENDEDOR(MATRICULA);
        
-- TABLA ITEMS FACTURAS
CREATE TABLE items_facturas
(NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY (NUMERO, CODIGO));

ALTER TABLE items_facturas ADD CONSTRAINT FK_FACTURAS
FOREIGN KEY (NUMERO)
REFERENCES TB_FACTURAS(NUMERO);
    