-- CREAR DB
CREATE DATABASE IF NOT EXISTS
	ventas_jugos
DEFAULT CHARSET
	UTF32;
    
-- CREAR SCHEMA
CREATE SCHEMA IF NOT EXISTS
	ventas_jugos;
    
-- ELIMINAR DB
DROP DATABASE IF EXISTS
	ventas_jugos;