CREATE DATABASE IF NOT EXISTS 
	VENTAS_JUGOS;
    
USE 
	VENTAS_JUGOS;
    
-- TABLA DE VENDEDORES
CREATE TABLE IF NOT EXISTS
	TB_VENDEDOR
    (
		MATRICULA VARCHAR(5) NOT NULL,
        NOMBRE VARCHAR(100) NULL,
        BARRIO VARCHAR(50) NULL,
        COMISION FLOAT NULL,
        FECHA_ADMISION DATE NULL,
        DE_VACACIONES BIT(1) NULL,
        
        PRIMARY KEY(MATRICULA)
    );
    
    
-- TABLA DE PRODUCTO
CREATE TABLE 
	TB_PRODUCTO
    (
		CODIGO VARCHAR(10) NOT NULL,
        DESCRIPCION VARCHAR(100) NULL,
        SABOR VARCHAR(50) NULL,
        TAMAÑO VARCHAR(50) NULL,
        ENVASE VARCHAR(50) NULL,
        PRECIO_LISTA FLOAT NULL,
        
        PRIMARY KEY(CODIGO)
    );
    
-- TABLA CLIENTES
CREATE TABLE IF NOT EXISTS
	TB_CLIENTE
    (
		DNI VARCHAR(11) NOT NULL,
        NOMBRE VARCHAR(100) DEFAULT NULL,
        DIRECCION VARCHAR(150) DEFAULT NULL,
        BARRIO VARCHAR(50) DEFAULT NULL,
        CIUDAD VARCHAR(50) DEFAULT NULL,
        ESTADO VARCHAR(45) DEFAULT NULL,
        CP VARCHAR(8) DEFAULT NULL,
        FECHA_NAC DATE DEFAULT NULL,
        EDAD INT(2) DEFAULT NULL,
        SEXO CHAR(1) DEFAULT NULL,
        LIMITE_CREDITO FLOAT DEFAULT NULL,
        VOLUMEN_COMPRA FLOAT DEFAULT NULL,
        PRIMERA_COMPRA BIT(1) DEFAULT NULL,
        
        PRIMARY KEY (DNI)
    );
    
-- TABLA FACTURAS
CREATE TABLE IF NOT EXISTS `ventas_jugos`.`tb_facturas` (
  `NUMERO` VARCHAR(5) NOT NULL,
  `FECHA` DATE NULL,
  `DNI` VARCHAR(11) NOT NULL,
  `MATRICULA` VARCHAR(5) NOT NULL,
  `IMPUESTO` FLOAT NULL,
  PRIMARY KEY (`NUMERO`));