-- BORRA EL PRODUCTO CON CODIGO
DELETE FROM TB_PRODUCTO WHERE CODIGO = '100100';

-- BORRA TODOS LOS PRODUCTOS DE 1 LITRO
DELETE FROM TB_PRODUCTO WHERE TAMAÑO = "1 Litro";

SELECT CODIGO_DEL_PRODUCTO FROM jugos_ventas.tabla_de_productos;

-- ELIMINA LOS REGISTROS CUYO CODIGO NO ESTA EN JUGOS_VENTAS.TABLA_DE_PRODUCTOS
DELETE  
	FROM tb_producto 
WHERE CODIGO NOT IN
(
	SELECT CODIGO_DEL_PRODUCTO FROM jugos_ventas.tabla_de_productos
);