USE VENTAS_JUGOS;

-- TABLA ITEMS FACTURAS
CREATE TABLE IF NOT EXISTS 
	TB_ITEMS_FACTURAS
	(
		NUMERO VARCHAR(5) NOT NULL,
        CODIGO VARCHAR(10) NOT NULL,
        CANTIDAD INT,
        PRECIO FLOAT,
        
        PRIMARY KEY(NUMERO,CODIGO)
    );
    
-- LLAVE FORANEA PARA NUMERO
ALTER TABLE 
	TB_ITEMS_FACTURAS 
		ADD CONSTRAINT FK_FACTURA
        FOREIGN KEY (NUMERO) REFERENCES TB_FACTURA (NUMERO);
        
-- LLAVE FORANEA PARA CODIGO
ALTER TABLE 
	TB_ITEMS_FACTURAS 
		ADD CONSTRAINT FK_PRODUCTO
        FOREIGN KEY (CODIGO) REFERENCES TB_PRODUCTO (CODIGO);