USE VENTAS_JUGOS;
-- INSERTAR DATOS DESDE CSV EN VENDEDORES
LOAD DATA INFILE 'vendedores.csv'
INTO TABLE TB_VENDEDOR
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

SELECT * FROM TB_VENDEDOR;