USE VENTAS_JUGOS;

-- CONSULTA LOS REGISTROS DE LA TABLA DE PRODUCTOS EN LA BD JUGOS_VENTAS
SELECT
	*
FROM jugos_ventas.tabla_de_productos;

-- CONSULTA LOS REGISTROS DE tablas_de_productos en la DB jugos_ventas, cuyo codigo no este presente en la tabla tb_producto de la DB ventas jugos y les asigna un alias
SELECT
	CODIGO_DEL_PRODUCTO AS CODIGO,
    NOMBRE_DEL_PRODUCTO AS DESCRIPCION,
    SABOR,
    TAMANO as TAMAÑO,
    ENVASE,
    PRECIO_DE_LISTA
FROM
	jugos_ventas.tabla_de_productos
WHERE CODIGO_DEL_PRODUCTO NOT IN
	(
		SELECT
			CODIGO
		FROM
			TB_PRODUCTO
    );
    
-- INSERCION MASIVA DE REGISTROS EN TB_PRODUCTO
INSERT INTO
	TB_PRODUCTO
SELECT
	CODIGO_DEL_PRODUCTO AS CODIGO,
    NOMBRE_DEL_PRODUCTO AS DESCRIPCION,
    SABOR,
    TAMANO as TAMAÑO,
    ENVASE,
    PRECIO_DE_LISTA
FROM
	jugos_ventas.tabla_de_productos
WHERE CODIGO_DEL_PRODUCTO NOT IN
	(
		SELECT
			CODIGO
		FROM
			TB_PRODUCTO
    );

-- CONSULTA LOS REGISTROS EN TB_PRODUCTO
SELECT * FROM TB_PRODUCTO;

-- INSERCION MASIVA EN TB_CLIENTE
INSERT INTO tb_cliente
SELECT DNI, NOMBRE, DIRECCION_1 AS DIRECCION,
BARRIO, CIUDAD, ESTADO, CP, FECHA_DE_NACIMIENTO 
AS FECHA_NACIMIENTO, EDAD, SEXO, LIMITE_DE_CREDITO
AS LIMITE_CREDITO, VOLUMEN_DE_COMPRA AS VOLUMEN_COMPRA,
PRIMERA_COMPRA FROM jugos_ventas.tabla_de_clientes
WHERE DNI NOT IN (SELECT DNI FROM tb_cliente);