USE VENTAS_JUGOS;

-- RENOMBRAR LA TABLA VENTAS
ALTER TABLE
	TB_VENTAS RENAME TB_FACTURA;
    
-- RENOMBRA LA TABLA ITEMS FACTURAS
ALTER TABLE items_facturas RENAME tb_items_facturas;
    
SHOW TABLES;