USE VENTAS_JUGOS;

-- CONSULTA LOS REGISTROS DE LA TABLA VENDEDOR EN LA BD VENTAS JUGOS
SELECT * FROM ventas_jugos.tb_vendedor;

-- CONSULTA LOS REGISTROA DE LA TABLA DE VENDEDORES EN LA BD JUGOS_VENTAS
SELECT * FROM jugos_ventas.tabla_de_vendedores;

-- UNE LAS TABLAS TB VENDEDOR Y TABLA DE VENDEDORES
SELECT 
	*
FROM
	TB_VENDEDOR A
INNER JOIN
	jugos_ventas.tabla_de_vendedores B
	ON A.MATRICULA = SUBSTRING(B.MATRICULA,3,3);
    
-- ACTUALIZA LA COLUMNA DE VACIONES ASIGNADO EL VALOR VACIONES DE LA TABLA B    
UPDATE 
	TB_VENDEDOR A
    INNER JOIN
    jugos_ventas.tabla_de_vendedores B
    ON A.MATRICULA = substring(B.MATRICULA,3,3)
SET A.DE_VACACIONES = B.VACACIONES;
