SELECT 
	*
FROM 
	TB_PRODUCTO;
    
-- ACTUALIZANDO EL PRECIO DE UN PRODUCTO
UPDATE 
	TB_PRODUCTO
SET
	PRECIO_LISTA = 5
WHERE 
	CODIGO = '1000889';
    
-- CONSULTA EL PRODUCTO CON CODIGO
SELECT 
	*
FROM 
	TB_PRODUCTO
WHERE
	CODIGO = '1000889';
    
-- ACTUALIZAR EL NOMBRE, TAMAÑO Y ENVASE DE UN PRODUCTO
UPDATE
	TB_PRODUCTO
SET
	DESCRIPCION = "Sabor de la montaña",
    TAMAÑO = '1Lt',
    ENVASE = "BOTELLA PET"
WHERE
	CODIGO = '1000889';
    
-- ACTUALIZAR EL VOLUMEN DE COMPRA DE UN CLIENTE
UPDATE 
	TB_CLIENTE
SET
	VOLUMEN_COMPRA = VOLUMEN_COMPRA/10;

-- CONSULTAR REGISTROS DE LA TABLA CLIENTE    
SELECT * FROM TB_CLIENTE;
