SELECT * FROM tbproducto;

-- CONSULTA LAS FILA DONDE EL SABOR SEA MARACUYA EN tbproducto
SELECT *
FROM tbproducto
WHERE sabor LIKE "%MARACUYA%";

-- CONSULTA LAS FILAS DONDE EL ENVASE SEA BOTELLA DE VIDRIO EN tbproducto
SELECT *
FROM tbproducto 
WHERE envase LIKE "%BOTELLA DE VIDRIO%";

-- CAMBIA EL NOMBRE DE LOS REGISTROS SABOR LIMON A CITRICO
UPDATE tbproducto 
SET sabor = "citrico" 
WHERE sabor LIKE "%Limon%";

-- SELECIONA TODOS LOS CAMPOS DONDE EL SABOR SEA CITRICO
SELECT * 
FROM tbproducto
WHERE sabor = "citrico";