USE jugos;
SELECT * FROM tbcliente;

-- FILTRA POR REGISTROS CON FECHA DE NACIMIENTO 1995-01-13
SELECT 
*
FROM tbcliente
WHERE fecha_nacimiento = '1995-01-13';

-- FILTRA POR REGISTROS CON FECHA DE NACIMIENTO ANTERIOR 1995-01-13
SELECT 
*
FROM tbcliente
WHERE fecha_nacimiento < '1995-01-13';

-- FILTRA POR REGISTROS CON FECHA DE NACIMIENTO ANTERIOR O IGUAL 1995-01-13
SELECT 
*
FROM tbcliente
WHERE fecha_nacimiento <= '1995-01-13';


-- FILTRA POR REGISTROS CON FECHA DE NACIMIENTO POSTERIOR 1995-01-13
SELECT 
*
FROM tbcliente
WHERE fecha_nacimiento > '1995-01-13';

-- FILTRA POR REGISTROS CON FECHA DE NACIMIENTO POSTERIOR 1995-01-13
SELECT 
*
FROM tbcliente
WHERE fecha_nacimiento >= '1995-01-13';

-- FILTRA POR REGISTROS CON FECHA DE NACIMIENTO SEA IGUAL AL AÑO 1995
SELECT 
*
FROM tbcliente
WHERE YEAR(fecha_nacimiento) = '1995';

-- FILTRA POR REGISTROS CON FECHA DE NACIMIENTO SEA IGUAL AL DIA 20
SELECT 
*
FROM tbcliente
WHERE DAY(fecha_nacimiento) = '20';