-- CONSULTA LA FACTURACION DE UNA FECHA ESPECIFICA
SELECT
	a.fecha,
    FLOOR(SUM(b.cantidad * b.precio))as FACTURACION
FROM
	facturas a
    INNER JOIN
    items b
ON a.numero = b.numero
WHERE a.fecha = '20240101';

-- LLAMA AL SP sp_venta
CALL sp_venta(
	'20240101', -- FECHA DE LA FACTURA
	20, -- NUMERO MAXIMO DE PRODUCTOS
	100 -- CANTIDAD MAXIMA DE LOS PRODUCTOS VENDIDOS
);

-- CONSULTA CUANTOS PRODUCTOS SE TIENEN
SELECT COUNT(*) FROM productos;
