/*
LA FORMULA PARA GENERAR UN NUMERO ALEATORIO EN UN RANGO DEFINICIO ES LA SIGUIENTE:
	RAND * ( (NUMERO MAXIMO) - (NUMERO MINUMO) + 1) + VALOR MINIMO 
*/
SELECT FLOOR(RAND() * (100 - 0 + 1) + 0) AS NUMERO_ALEATORIO;