-- CREA LA TB facturacion
CREATE TABLE facturacion(
FECHA DATE NULL,
VENTA_TOTAL FLOAT
);

-- BORRA LOS TRIGGERS TG_FACTURACION
DROP TRIGGER TG_FACTURACION_INSERT;
DROP TRIGGER TG_FACTURACION_DELETE;
DROP TRIGGER TG_FACTURACION_UPDATE;

-- CREA UN TG PARA INSERT facturacion
DELIMITER //
CREATE TRIGGER TG_FACTURACION_INSERT 
AFTER INSERT ON items
FOR EACH ROW BEGIN
  CALL sp_triggers;
END //

-- CREA UN TG PARA DELETE facturacion
DELIMITER //
CREATE TRIGGER TG_FACTURACION_DELETE
AFTER DELETE ON items
FOR EACH ROW BEGIN
  CALL sp_triggers;
END //

-- CREA UN TH PARA UPDATE EN facturacion
DELIMITER //
CREATE TRIGGER TG_FACTURACION_UPDATE
AFTER UPDATE ON items
FOR EACH ROW BEGIN
  CALL sp_triggers;
END //

-- LLAMA AL SP sp_venta
CALL sp_venta(
	'20240829', -- FECHA DE LA FACTURA
	15, -- NUMERO MAXIMO DE PRODUCTOS
	100 -- CANTIDAD MAXIMA DE LOS PRODUCTOS VENDIDOS
);

-- CONSULTA LA FACTURACION DE UNA FECHA ESPECIFICA
SELECT
	a.fecha,
    FLOOR(SUM(b.cantidad * b.precio))as FACTURACION
FROM
	facturas a
    INNER JOIN
    items b
ON a.numero = b.numero
WHERE a.fecha = '20240829';
